### ISSUE TITLE
Doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by haeckle** [rockiger/recentpages#1]
Installed zim from the ubuntu repository (version 0.72.0) and this plugin as described in the Readme but it didn't show up in the plugin list.

**Comment by rockiger** [comment]
The plugin need to get updated I guess. Right now I don't have any plans to update the plugin.

I didn't use Zim for years. I switched to [https://fulcrum.wiki](https://fulcrum.wiki).

Having said that, I am happy to accept pull requests.
